name: main

on:
  push:
    branches:
      - feature/deploy-dev
      - main
    paths-ignore:
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyspark==3.5.0 pytest chispa

      - name: Run Pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m pytest tests/

  deploy-dev:
    needs: test
    name: deploy to dev
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/deploy-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy to Dev
        run: databricks bundle deploy -t dev

  deploy-prod:
    needs: test
    name: deploy to prod
    environment: production
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy to Prod
        run: databricks bundle deploy -t prod